name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  bump:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: ${{ vars.TARGET_REPO }}

      - uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/${{ vars.TARGET_REPO }}
          token: ${{ steps.app-token.outputs.token }}

      - env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          BOT: ${{ steps.app-token.outputs.app-slug }}[bot]
        run: |
          kustomize edit set image "app=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA"

          git config user.name "$BOT"
          git config user.email "$(gh api "/users/$BOT" --jq .id)+$BOT@users.noreply.github.com"
          git switch -c "bump/$GITHUB_SHA"
          git commit -am "Bump app to ${GITHUB_SHA::7}"
          git push origin HEAD
          gh pr create --fill
